---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-14.04
    customize:
      cpus: 1
      memory: 512

suites:
- name: default
  run_list: ['recipe[client-rs-haproxy::default]']
  provisioner:
      solo_rb:
        log_location: /var/log/chef-solo.log
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['10.10.1.1']
      private_ips: ['10.0.2.15']
